# Generated by Django 5.0 on 2024-01-01 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_game_ranking_game_overall_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='script_path',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='thumbnail_path',
            field=models.ImageField(null=True, upload_to='images'),
        ),
    ]
