# Generated by Django 5.0.1 on 2024-01-06 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_category_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, default=''),
        ),
        migrations.RemoveField(
            model_name='game',
            name='category',
        ),
        migrations.AddField(
            model_name='game',
            name='category',
            field=models.ManyToManyField(null=True, to='main.category'),
        ),
    ]
