# Generated by Django 5.0.1 on 2024-01-06 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_category_slug_remove_game_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='category',
        ),
        migrations.AddField(
            model_name='category',
            name='games',
            field=models.ManyToManyField(to='main.game'),
        ),
    ]
