# Generated by Django 5.0.1 on 2024-01-07 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_remove_ranking_id_alter_ranking_player'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='description',
            field=models.CharField(max_length=9999, null=True),
        ),
    ]
